### ISSUE TITLE
Maybe sort the output

### ISSUE THREAD

**Issue by hupfdule** [iafan/cwalk#6]
Related to #3 I open this issue since it behaves differently than the builtin `filepath/Walk()` which is not really expected.

The builtin `filepath/Walk()` always sorts its output. Using the same API as `filepath/Walk()` cwalk should behave the same (or clearly state this difference in a prominent place).

Maybe adding an option for this behaviour would be appropriate (as sorting is not always necessary), but the default should resemble the behaviour of the builtin `filepath/Walk()`.

**Comment by iafan** [comment]
Thanks for the suggestion. CWalk is by design supposed to process files _concurrently_. With this concurrency in mind, sorting doesn't make sense, because the pool of files is being processed in multiple threads and at their own pace, so the sequence in which files are processed can never be guaranteed. It is a responsibility of the calling code to sort the final results, if needed.

This was also explicitly stated in https://github.com/iafan/cwalk/blob/master/cwalk.go#L66-L67

**Comment by hupfdule** [comment]
Many thanks. My main consideration was that cwalk is still faster than `filepath/Walk()` even when the full result is sorted afterwards and that the output would be more similar to `filepath/Walk()`.

Anyway, I am fine with your decision to leave sorting to the caller. 

Maybe it could be stated in the README and the `Walk()` method that this behaviour differes from the builtin even though the API is the same.

**Comment by iafan** [comment]
Done. Thanks for the suggestion!
